version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:stable
    restart: always
    ports:
      - 8088:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: db_example
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    restart: always
    build: .
    container_name: v-springbootdeploy
    image: sprintbootdeploy:test
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: ["/wait-for-it.sh","mysql:3306","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]